Add an ENVIRON variable and use it to set deployment name
Changes the deployment-related scripts to expect an argument for which
environment to deploy. They'll look for a `.env.ENVIRON` file to set the
environment variables and will create claudia-ENVIRON.json and
.api-id-ENVIRON files rather than always using the same unqualified names.

Using separate claudia.json files means the config file is now given as
an argument, rather than using the default, and they go in a subdirectory.

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -3,10 +3,9 @@
 set -e
 
 DEPLOY_NEW=""
-ENVIRON="dev"
 
 function usage() {
-    echo -n "Usage: $(basename "${0}") [OPTION]
+    echo -n "Usage: $(basename "${0}") [OPTION] ENVIRON
 Publish project in development to AWS Lambda
 Options:
     --new     Deploy as a new lambda
@@ -15,31 +14,43 @@ Options:
 }
 
 function main() {
+    ENVIRON="${1}"
+
     docker-compose -f docker-compose.yml \
                    --env-file ".env.${ENVIRON}" \
                    run --rm --no-deps -e NODE_ENV=production tiler yarn deploy${DEPLOY_NEW:+-new}
 
     # Deploy CloudFront proxy
-    docker-compose run terraform init
-    docker-compose run --rm -e TF_VAR_source_id=$(<src/tiler/.api-id) terraform apply -auto-approve && \
-    echo "Success! Your tiles will be available at the above URL shortly."
+    docker-compose --env-file ".env.${ENVIRON}" run terraform init
+    docker-compose --env-file ".env.${ENVIRON}" \
+            run --rm -e TF_VAR_source_id=$(<src/tiler/.api-id-${ENVIRON}) \
+            terraform apply -auto-approve && \
+        echo "Success! Your tiles will be available at the above URL shortly."
 }
 
 if [ "${BASH_SOURCE[0]}" = "${0}" ]
 then
-    case "$1" in
-        -n| --new)
-            DEPLOY_NEW='--new'
-            shift
-            ;;
-        -h| --help)
-            usage
-            exit
-            ;;
-        *)
-            ENVIRON=$1
-            shift
-    esac
-    echo "Deploying to environment '${ENVIRON}'"
-    main ENVIRON
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -n| --new)
+                DEPLOY_NEW='--new'
+                shift
+                ;;
+            -h| --help)
+                usage
+                exit
+                ;;
+            *)
+                ENVIRON=$1
+                shift
+        esac
+    done
+    if [ -z "${ENVIRON}" ]; then
+        echo "Required ENVIRON argument is missing."
+        usage
+        exit 1
+    else
+        echo "Deploying to environment '${ENVIRON}'"
+    fi
+    main $ENVIRON
 fi
diff --git a/src/tiler/scripts/deploy b/src/tiler/scripts/deploy
--- a/src/tiler/scripts/deploy
+++ b/src/tiler/scripts/deploy
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-yarn claudia update --no-optional-dependencies \
+if [ -z "${ENVIRON}" ]; then
+   echo 'Required $ENVIRON variable not set.'
+   exit 1
+fi
+
+yarn claudia update \
+   --config claudia/claudia-${ENVIRON}.json \
+   --no-optional-dependencies \
    ${LAMBDA_TIMEOUT:+--timeout ${LAMBDA_TIMEOUT}} \
    ${LAMBDA_MEMORY:+--memory ${LAMBDA_MEMORY}} \
    ${LAMBDA_SECURITY_GROUPS:+--security-group-ids ${LAMBDA_SECURITY_GROUPS}} \
diff --git a/src/tiler/scripts/deploy-new b/src/tiler/scripts/deploy-new
--- a/src/tiler/scripts/deploy-new
+++ b/src/tiler/scripts/deploy-new
@@ -1,11 +1,21 @@
 #!/bin/bash
 
-yarn claudia create --no-optional-dependencies --api-module src/api \
-    --name ${PROJECT_NAME} --region ${LAMBDA_REGION} \
+if [ -z "${ENVIRON}" ]; then
+   echo 'Required $ENVIRON variable not set.'
+   exit 1
+elif [ -z "${PROJECT_NAME}" ]; then
+   echo 'Required $PROJECT_NAME variable not set.'
+   exit 1
+fi
+
+yarn claudia create \
+    --config claudia/claudia-${ENVIRON}.json \
+    --no-optional-dependencies --api-module src/api \
+    --name "${PROJECT_NAME}-${USER}-${ENVIRON}" --region ${LAMBDA_REGION} \
     ${LAMBDA_ROLE:+--role ${LAMBDA_ROLE}} \
     ${LAMBDA_TIMEOUT:+--timeout ${LAMBDA_TIMEOUT}} \
     ${LAMBDA_MEMORY:+--memory ${LAMBDA_MEMORY}} \
     ${LAMBDA_SECURITY_GROUPS:+--security-group-ids ${LAMBDA_SECURITY_GROUPS}} \
     ${LAMBDA_SUBNETS:+--subnet-ids ${LAMBDA_SUBNETS}} \
     --set-env TILEGARDEN_DB_HOST=${TILEGARDEN_DB_HOST},TILEGARDEN_DB_NAME=${TILEGARDEN_DB_NAME},TILEGARDEN_DB_PASSWORD=${TILEGARDEN_DB_PASSWORD},TILEGARDEN_DB_PORT=${TILEGARDEN_DB_PORT},TILEGARDEN_DB_USER=${TILEGARDEN_DB_USER} \
-&& yarn parse-id
+&& jq -r '.api.id' claudia/claudia-${ENVIRON}.json > .api-id-${ENVIRON}
