Update clean/destroy scripts to tidy up terraform/claudia artifacts
Former-commit-id: 5730ec4566a0ef42a834f6dd288c6748f98e0f1c

diff --git a/node_lambnik/scripts/destroy b/node_lambnik/scripts/destroy
--- a/node_lambnik/scripts/destroy
+++ b/node_lambnik/scripts/destroy
@@ -16,8 +16,15 @@ function main() {
 	echo
 	if [[ $REPLY =~ ^[yY][eE][sS]$ ]]
 	then
-		docker-compose run tiler yarn destroy;
-		docker-compose run terraform destroy -auto-approve;
+		# This command ALSO tried to destroy your lambda's IAM role.
+		# It will probably fail to do so, but it will delete the lambda
+		# and API Gateway FIRST, so it's fine.
+		docker-compose run tiler yarn destroy || true;
+		docker-compose run tiler rm claudia.json;
+
+		docker-compose run -e TF_VAR_source_id=$(<src/tiler/.api-id) terraform destroy -auto-approve;
+		docker-compose run --entrypoint rm terraform -rf .terraform terraform.tfstate terraform.tfstate.backup;
+
 	else
 		echo "Aborting destroy"
 	fi
